[package]
name = "rgis-ui"
version = "0.1.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
publish = false

[dependencies]
bevy = { version = "0.14", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_ui",
    "wayland",
    "png",
] }
bevy_egui = "0.30"
egui_plot = "0.29"
geo-features = { path = "../geo-features" }
geo-file-loader = { path = "../geo-file-loader" }
geo-projected = { path = "../geo-projected" }
dark-light = "1.0"
rfd = "0.15"
rgis-geo-ops = { path = "../rgis-geo-ops" }
rgis-layer-id = { path = "../rgis-layer-id" }
rgis-layers = { path = "../rgis-layers" }
rgis-library = { path = "../rgis-library" }
rgis-events = { path = "../rgis-events" }
rgis-mouse = { path = "../rgis-mouse" }
rgis-settings = { path = "../rgis-settings" }
rgis-units = { path = "../rgis-units" }
bevy_jobs = { git = "https://github.com/frewsxcv/bevy_jobs" }
geo = "0.29"
geo-geodesy = "1"
thiserror = "2"
crs-definitions = "0.3"
geodesy = "0.13"
