[workspace]
members = [
    "geo-features",
    "geo-geom-type",
    "geo-projected",
    "rgis-camera",
    "rgis-cli",
    "rgis-events",
    "rgis-file-loader",
    "rgis-geo-ops",
    "rgis-keyboard",
    "rgis-layer-id",
    "rgis-layers",
    "rgis-library",
    "rgis-mouse",
    "rgis-network",
    "rgis-renderer",
    "rgis-settings",
    "rgis-ui",
    "rgis-units",
    "rgis",
    "time-logger",
    "transform",
    "typed-num",
]
resolver = "2"

[build]
# https://github.com/rustwasm/wasm-bindgen/issues/4211
strip = true

[profile.dev]
# https://github.com/rustwasm/wasm-bindgen/issues/4211
strip = true

[profile.release]
debug = true
# https://github.com/rustwasm/wasm-bindgen/issues/4211
strip = true

# https://github.com/rustwasm/wasm-bindgen/issues/4211
[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
