[package]
name = "transform"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
geodesy = { version = "0.13", default-features = false }
crs-definitions = "0.3"
geo = "0.29"
thiserror = "1"
